import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('id'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'id': {
      'app_title': 'Cashbook',
      'app_tagline': 'Catat Keuangan Cerdas & Aman',
      // Nav
      'nav_home': 'Beranda',
      'nav_transactions': 'Transaksi',
      'nav_report': 'Laporan',
      'nav_account': 'Akun',
      // Home
      'total_balance': 'Total Saldo Kas',
      'cash_in': 'Masuk',
      'cash_out': 'Keluar',
      'add_income': 'Pemasukan',
      'add_expense': 'Pengeluaran',
      'manage_books': 'Kelola Buku',
      'recent_transactions': 'Transaksi Terakhir',
      'see_all': 'Lihat Semua',
      'no_transactions': 'Belum ada transaksi di buku ini',
      'no_transactions_sub': 'Tekan tombol di atas untuk mencatat transaksi',
      'sync_drive': 'Sinkronkan ke Google Drive',
      'sync_success': 'Data berhasil disinkronkan ke Google Drive!',
      'sync_failed': 'Sinkronisasi gagal, periksa koneksi internet.',
      'read_only_banner': 'Buku ini bersifat Read-Only. Anda tidak dapat menambah atau mengubah transaksi.',
      'closed_book_banner': 'Buku Kas ini telah Ditutup (Closed). Buka kembali untuk menambah transaksi baru.',
      // Book
      'select_book': 'Pilih Buku Kas',
      'active_books': 'Buku Aktif',
      'closed_books': 'Buku Ditutup',
      'close_book': 'Tutup Buku Kas',
      'reopen_book': 'Buka Kembali Buku',
      'close_book_confirm_title': 'Tutup Buku Kas Ini?',
      'close_book_confirm_desc': 'Setelah ditutup, transaksi tidak dapat ditambah atau diubah sampai buku dibuka kembali.',
      'reopen_book_confirm_title': 'Buka Kembali Buku Kas?',
      'reopen_book_confirm_desc': 'Buku kas akan diaktifkan kembali sehingga Anda dapat mencatat transaksi baru.',
      'share_file': 'Bagikan Berkas (.cbshare)',
      'share_link': 'Bagikan Tautan Live',
      'share_file_closed_only': 'Buku kas harus ditutup (Closed) terlebih dahulu sebelum dapat dibagikan sebagai berkas laporan rekapan.',
      'close_now': 'Tutup Sekarang',
      'cancel': 'Batal',
      'book_name': 'Nama Buku Kas',
      'select_icon': 'Pilih Ikon',
      'select_color': 'Pilih Warna Tema',
      'save': 'Simpan',
      'update': 'Perbarui',
      'status_open': 'Terbuka',
      'status_closed': 'Ditutup',
      // Transactions
      'history_transactions': 'Riwayat Transaksi',
      'search_placeholder': 'Cari catatan atau kategori...',
      'all': 'Semua',
      'nominal_income': 'Nominal Pemasukan',
      'nominal_expense': 'Nominal Pengeluaran',
      'category': 'Kategori',
      'transaction_date': 'Tanggal Transaksi',
      'notes_optional': 'Catatan (Opsional)',
      'notes_hint_income': 'Tulis keterangan pemasukan...',
      'notes_hint_expense': 'Tulis keterangan pengeluaran...',
      'detail_transaction': 'Detail Transaksi',
      'delete_to_trash': 'Pindahkan ke Sampah',
      'delete_confirm_desc': 'Data ini akan dipindahkan ke Sampah (Trash) dan dapat dipulihkan kapan saja.',
      // Report
      'financial_report': 'Laporan Keuangan',
      'this_month': 'Bulan Ini',
      'last_month': 'Bulan Lalu',
      'this_year': 'Tahun Ini',
      'custom_range': 'Kustom',
      'net_balance': 'Selisih / Saldo Bersih',
      'cash_flow_comparison': 'Perbandingan Arus Kas',
      'expense_by_category': 'Rincian Pengeluaran per Kategori',
      'export_pdf': 'Ekspor PDF',
      'export_excel': 'Ekspor Excel',
      // Account
      'account_settings': 'Akun & Pengaturan',
      'drive_sync_title': 'Google Drive Cloud Sync',
      'drive_sync_desc': 'Tersimpan di file data.cashbook pribadi',
      'sync_now': 'Sinkron',
      'manage_categories': 'Kelola Kategori',
      'import_cbshare': 'Impor Buku Kas (.cbshare)',
      'import_cbshare_sub': 'Buka file yang dibagikan orang lain',
      'trash_menu': 'Sampah (Trash)',
      'app_theme': 'Tema Tampilan',
      'language': 'Bahasa (Language)',
      'pin_security': 'Kunci PIN',
      'biometric_security': 'Kunci Biometrik',
      'logout': 'Keluar Akun Google',
    },
    'en': {
      'app_title': 'Cashbook',
      'app_tagline': 'Smart & Secure Financial Tracking',
      // Nav
      'nav_home': 'Home',
      'nav_transactions': 'Transactions',
      'nav_report': 'Report',
      'nav_account': 'Account',
      // Home
      'total_balance': 'Total Balance',
      'cash_in': 'Income',
      'cash_out': 'Expense',
      'add_income': 'Income',
      'add_expense': 'Expense',
      'manage_books': 'Manage Books',
      'recent_transactions': 'Recent Transactions',
      'see_all': 'See All',
      'no_transactions': 'No transactions in this book yet',
      'no_transactions_sub': 'Tap the buttons above to record transactions',
      'sync_drive': 'Sync to Google Drive',
      'sync_success': 'Data successfully synced with Google Drive!',
      'sync_failed': 'Sync failed, please check internet connection.',
      'read_only_banner': 'This book is Read-Only. You cannot add or modify transactions.',
      'closed_book_banner': 'This Cashbook is Closed. Reopen it to record new transactions.',
      // Book
      'select_book': 'Select Cashbook',
      'active_books': 'Active Books',
      'closed_books': 'Closed Books',
      'close_book': 'Close Book',
      'reopen_book': 'Reopen Book',
      'close_book_confirm_title': 'Close this Cashbook?',
      'close_book_confirm_desc': 'Once closed, transactions cannot be added or edited until the book is reopened.',
      'reopen_book_confirm_title': 'Reopen this Cashbook?',
      'reopen_book_confirm_desc': 'The cashbook will be reopened allowing you to record new transactions.',
      'share_file': 'Share File (.cbshare)',
      'share_link': 'Share Live Link',
      'share_file_closed_only': 'Cashbook must be closed before it can be shared as a finalized report file.',
      'close_now': 'Close Now',
      'cancel': 'Cancel',
      'book_name': 'Cashbook Name',
      'select_icon': 'Select Icon',
      'select_color': 'Select Theme Color',
      'save': 'Save',
      'update': 'Update',
      'status_open': 'Open',
      'status_closed': 'Closed',
      // Transactions
      'history_transactions': 'Transaction History',
      'search_placeholder': 'Search note or category...',
      'all': 'All',
      'nominal_income': 'Income Amount',
      'nominal_expense': 'Expense Amount',
      'category': 'Category',
      'transaction_date': 'Transaction Date',
      'notes_optional': 'Notes (Optional)',
      'notes_hint_income': 'Enter income description...',
      'notes_hint_expense': 'Enter expense description...',
      'detail_transaction': 'Transaction Details',
      'delete_to_trash': 'Move to Trash',
      'delete_confirm_desc': 'This item will be moved to Trash and can be restored at any time.',
      // Report
      'financial_report': 'Financial Report',
      'this_month': 'This Month',
      'last_month': 'Last Month',
      'this_year': 'This Year',
      'custom_range': 'Custom',
      'net_balance': 'Net Balance',
      'cash_flow_comparison': 'Cash Flow Comparison',
      'expense_by_category': 'Expense by Category',
      'export_pdf': 'Export PDF',
      'export_excel': 'Export Excel',
      // Account
      'account_settings': 'Account & Settings',
      'drive_sync_title': 'Google Drive Cloud Sync',
      'drive_sync_desc': 'Stored in your personal data.cashbook file',
      'sync_now': 'Sync',
      'manage_categories': 'Manage Categories',
      'import_cbshare': 'Import Cashbook (.cbshare)',
      'import_cbshare_sub': 'Open files shared by others',
      'trash_menu': 'Trash',
      'app_theme': 'Theme Mode',
      'language': 'Language',
      'pin_security': 'PIN Lock',
      'biometric_security': 'Biometric Lock',
      'logout': 'Sign Out Google Account',
    },
    'es': {
      'app_title': 'Cashbook',
      'app_tagline': 'Control Financiero Inteligente y Seguro',
      // Nav
      'nav_home': 'Inicio',
      'nav_transactions': 'Transacciones',
      'nav_report': 'Informe',
      'nav_account': 'Cuenta',
      // Home
      'total_balance': 'Saldo Total',
      'cash_in': 'Ingresos',
      'cash_out': 'Gastos',
      'add_income': 'Ingreso',
      'add_expense': 'Gasto',
      'manage_books': 'Gestionar Libros',
      'recent_transactions': 'Transacciones Recientes',
      'see_all': 'Ver Todo',
      'no_transactions': 'Aún no hay transacciones en este libro',
      'no_transactions_sub': 'Toca los botones de arriba para registrar transacciones',
      'sync_drive': 'Sincronizar con Google Drive',
      'sync_success': '¡Datos sincronizados con éxito en Google Drive!',
      'sync_failed': 'Error de sincronización, revisa tu conexión a internet.',
      'read_only_banner': 'Este libro es de solo lectura. No puedes añadir ni editar transacciones.',
      'closed_book_banner': 'Este libro está cerrado. Reábrelo para registrar nuevas transacciones.',
      // Book
      'select_book': 'Seleccionar Libro',
      'active_books': 'Libros Activos',
      'closed_books': 'Libros Cerrados',
      'close_book': 'Cerrar Libro',
      'reopen_book': 'Reabrir Libro',
      'close_book_confirm_title': '¿Cerrar este Libro?',
      'close_book_confirm_desc': 'Una vez cerrado, las transacciones no se pueden modificar hasta que se reabra.',
      'reopen_book_confirm_title': '¿Reabrir este Libro?',
      'reopen_book_confirm_desc': 'El libro se activará de nuevo permitiendo registrar nuevas transacciones.',
      'share_file': 'Compartir Archivo (.cbshare)',
      'share_link': 'Compartir Enlace en Vivo',
      'share_file_closed_only': 'El libro debe estar cerrado antes de poder compartirlo como archivo de resumen final.',
      'close_now': 'Cerrar Ahora',
      'cancel': 'Cancelar',
      'book_name': 'Nombre del Libro',
      'select_icon': 'Seleccionar Icono',
      'select_color': 'Seleccionar Color',
      'save': 'Guardar',
      'update': 'Actualizar',
      'status_open': 'Abierto',
      'status_closed': 'Cerrado',
      // Transactions
      'history_transactions': 'Historial de Transacciones',
      'search_placeholder': 'Buscar nota o categoría...',
      'all': 'Todo',
      'nominal_income': 'Monto de Ingreso',
      'nominal_expense': 'Monto de Gasto',
      'category': 'Categoría',
      'transaction_date': 'Fecha de Transacción',
      'notes_optional': 'Notas (Opcional)',
      'notes_hint_income': 'Escribe descripción del ingreso...',
      'notes_hint_expense': 'Escribe descripción del gasto...',
      'detail_transaction': 'Detalles de la Transacción',
      'delete_to_trash': 'Mover a la Papelera',
      'delete_confirm_desc': 'Este elemento se moverá a la Papelera y podrá recuperarse en cualquier momento.',
      // Report
      'financial_report': 'Informe Financiero',
      'this_month': 'Este Mes',
      'last_month': 'Mes Pasado',
      'this_year': 'Este Año',
      'custom_range': 'Personalizado',
      'net_balance': 'Saldo Neto',
      'cash_flow_comparison': 'Comparación de Flujo de Caja',
      'expense_by_category': 'Gastos por Categoría',
      'export_pdf': 'Exportar PDF',
      'export_excel': 'Exportar Excel',
      // Account
      'account_settings': 'Cuenta y Configuración',
      'drive_sync_title': 'Sincronización Google Drive',
      'drive_sync_desc': 'Guardado en tu archivo personal data.cashbook',
      'sync_now': 'Sincronizar',
      'manage_categories': 'Gestionar Categorías',
      'import_cbshare': 'Importar Libro (.cbshare)',
      'import_cbshare_sub': 'Abrir archivos compartidos por otros',
      'trash_menu': 'Papelera',
      'app_theme': 'Tema',
      'language': 'Idioma',
      'pin_security': 'Bloqueo PIN',
      'biometric_security': 'Bloqueo Biométrico',
      'logout': 'Cerrar Sesión de Google',
    },
  };

  String tr(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['id']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['id', 'en', 'es'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
