import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('id'));
  }

  static const _localizedValues = <String, Map<String, String>>{
    'id': {
      'app_title': 'Cashbook',
      'app_tagline': 'Catat Keuangan Cerdas & Aman',
      // Nav
      'nav_home': 'Beranda',
      'nav_transactions': 'Transaksi',
      'nav_report': 'Laporan',
      'nav_account': 'Akun',
      // Home
      'total_balance': 'Total Saldo Kas',
      'cash_in': 'Masuk',
      'cash_out': 'Keluar',
      'add_income': 'Pemasukan',
      'add_expense': 'Pengeluaran',
      'manage_books': 'Kelola Buku',
      'recent_transactions': 'Transaksi Terakhir',
      'see_all': 'Lihat Semua',
      'no_transactions': 'Belum ada transaksi di buku ini',
      'no_transactions_sub': 'Tekan tombol di atas untuk mencatat transaksi',
      'sync_drive': 'Sinkronkan ke Google Drive',
      'sync_success': 'Data berhasil disinkronkan ke Google Drive!',
      'sync_failed': 'Sinkronisasi gagal, periksa koneksi internet.',
      'read_only_banner': 'Buku ini bersifat Read-Only. Anda tidak dapat menambah atau mengubah transaksi.',
      'closed_book_banner': 'Buku Kas ini telah Ditutup (Closed). Buka kembali untuk menambah transaksi baru.',
      // Book
      'select_book': 'Pilih Buku Kas',
      'active_books': 'Buku Aktif',
      'closed_books': 'Buku Ditutup',
      'close_book': 'Tutup Buku Kas',
      'reopen_book': 'Buka Kembali Buku',
      'close_book_confirm_title': 'Tutup Buku Kas Ini?',
      'close_book_confirm_desc': 'Setelah ditutup, transaksi tidak dapat ditambah atau diubah sampai buku dibuka kembali.',
      'reopen_book_confirm_title': 'Buka Kembali Buku Kas?',
      'reopen_book_confirm_desc': 'Buku kas akan diaktifkan kembali sehingga Anda dapat mencatat transaksi baru.',
      'share_file': 'Bagikan Berkas (.cbshare)',
      'share_link': 'Bagikan Tautan Live',
      'share_file_closed_only': 'Buku kas harus ditutup (Closed) terlebih dahulu sebelum dapat dibagikan sebagai berkas laporan rekapan.',
      'close_now': 'Tutup Sekarang',
      'cancel': 'Batal',
      'book_name': 'Nama Buku Kas',
      'select_icon': 'Pilih Ikon',
      'select_color': 'Pilih Warna Tema',
      'save': 'Simpan',
      'update': 'Perbarui',
      'delete': 'Hapus',
      'edit': 'Ubah',
      'status_open': 'Terbuka',
      'status_closed': 'Ditutup',
      'add_book': 'Tambah Buku Kas',
      'new_book': 'Buku Baru',
      'create_first_book': 'Buat Buku Kas Pertama',
      'create_first_book_desc': 'Mulai catat keuangan Anda dengan membuat buku kas perdana.',
      'start_now': 'Mulai Sekarang',
      // Transactions
      'history_transactions': 'Riwayat Transaksi',
      'search_placeholder': 'Cari catatan atau kategori...',
      'all': 'Semua',
      'nominal_income': 'Nominal Pemasukan',
      'nominal_expense': 'Nominal Pengeluaran',
      'category': 'Kategori',
      'transaction_date': 'Tanggal Transaksi',
      'notes_optional': 'Catatan (Opsional)',
      'notes_hint_income': 'Tulis keterangan pemasukan...',
      'notes_hint_expense': 'Tulis keterangan pengeluaran...',
      'detail_transaction': 'Detail Transaksi',
      'delete_to_trash': 'Pindahkan ke Sampah',
      'delete_confirm_desc': 'Data ini akan dipindahkan ke Sampah (Trash) dan dapat dipulihkan kapan saja.',
      'amount': 'Nominal',
      'choose_category': 'Pilih Kategori',
      'save_transaction': 'Simpan Transaksi',
      'edit_transaction': 'Ubah Transaksi',
      'enter_valid_amount': 'Masukkan nominal yang valid',
      'please_select_category': 'Silakan pilih kategori',
      'transaction_saved': 'Transaksi berhasil disimpan',
      'transaction_deleted': 'Transaksi berhasil dipindahkan ke sampah',
      'date': 'Tanggal',
      'time': 'Waktu',
      'notes': 'Catatan',
      'quick_amounts': 'Nominal Cepat',
      'no_transactions_found': 'Tidak ada transaksi yang cocok',
      // Report
      'financial_report': 'Laporan Keuangan',
      'this_month': 'Bulan Ini',
      'last_month': 'Bulan Lalu',
      'this_year': 'Tahun Ini',
      'custom_range': 'Kustom',
      'net_balance': 'Selisih / Saldo Bersih',
      'cash_flow_comparison': 'Perbandingan Arus Kas',
      'expense_by_category': 'Rincian Pengeluaran per Kategori',
      'export_pdf': 'Ekspor PDF',
      'export_excel': 'Ekspor Excel',
      'no_report_data': 'Belum ada data untuk periode ini',
      // Categories
      'income_categories': 'Kategori Masuk',
      'expense_categories': 'Kategori Keluar',
      'add_category': 'Tambah Kategori',
      'edit_category': 'Ubah Kategori',
      'category_name': 'Nama Kategori',
      'cannot_delete_default': 'Kategori default tidak dapat dihapus',
      'delete_category_confirm': 'Apakah Anda yakin ingin menghapus kategori ini?',
      // Trash
      'trash_title': 'Sampah (Trash)',
      'tab_cashbooks': 'Buku Kas',
      'tab_transactions': 'Transaksi',
      'restore': 'Pulihkan',
      'delete_permanent': 'Hapus Permanen',
      'empty_trash_cashbooks': 'Tidak ada buku kas di sampah',
      'empty_trash_transactions': 'Tidak ada transaksi di sampah',
      'restore_success': 'Data berhasil dipulihkan',
      'delete_permanent_confirm': 'Data ini akan dihapus secara permanen dan tidak dapat dipulihkan lagi. Lanjutkan?',
      // Account
      'account_settings': 'Akun & Pengaturan',
      'drive_sync_title': 'Google Drive Cloud Sync',
      'drive_sync_desc': 'Tersimpan di file data.cashbook pribadi',
      'sync_now': 'Sinkron',
      'manage_categories': 'Kelola Kategori',
      'import_cbshare': 'Impor Buku Kas (.cbshare)',
      'import_cbshare_sub': 'Buka file yang dibagikan orang lain',
      'trash_menu': 'Sampah (Trash)',
      'app_theme': 'Tema Tampilan',
      'language': 'Bahasa',
      'pin_security': 'Kunci PIN',
      'biometric_security': 'Kunci Biometrik',
      'logout': 'Keluar Akun Google',
      'set_pin': 'Atur PIN Keamanan (6 Digit)',
      'enter_pin': 'Masukkan PIN 6 Digit',
      'pin_set_success': 'PIN keamanan berhasil diaktifkan',
      'pin_removed': 'PIN keamanan dinonaktifkan',
      'biometric_enabled': 'Kunci biometrik diaktifkan',
      'biometric_disabled': 'Kunci biometrik dinonaktifkan',
      'system_theme': 'Sistem',
      'light_theme': 'Terang',
      'dark_theme': 'Gelap',
      'select_language': 'Pilih Bahasa',
    },
    'en': {
      'app_title': 'Cashbook',
      'app_tagline': 'Smart & Secure Financial Tracking',
      // Nav
      'nav_home': 'Home',
      'nav_transactions': 'Transactions',
      'nav_report': 'Report',
      'nav_account': 'Account',
      // Home
      'total_balance': 'Total Balance',
      'cash_in': 'Income',
      'cash_out': 'Expense',
      'add_income': 'Income',
      'add_expense': 'Expense',
      'manage_books': 'Manage Books',
      'recent_transactions': 'Recent Transactions',
      'see_all': 'See All',
      'no_transactions': 'No transactions in this book yet',
      'no_transactions_sub': 'Tap the buttons above to record transactions',
      'sync_drive': 'Sync to Google Drive',
      'sync_success': 'Data successfully synced with Google Drive!',
      'sync_failed': 'Sync failed, please check internet connection.',
      'read_only_banner': 'This book is Read-Only. You cannot add or modify transactions.',
      'closed_book_banner': 'This Cashbook is Closed. Reopen it to record new transactions.',
      // Book
      'select_book': 'Select Cashbook',
      'active_books': 'Active Books',
      'closed_books': 'Closed Books',
      'close_book': 'Close Book',
      'reopen_book': 'Reopen Book',
      'close_book_confirm_title': 'Close this Cashbook?',
      'close_book_confirm_desc': 'Once closed, transactions cannot be added or edited until the book is reopened.',
      'reopen_book_confirm_title': 'Reopen this Cashbook?',
      'reopen_book_confirm_desc': 'The cashbook will be reopened allowing you to record new transactions.',
      'share_file': 'Share File (.cbshare)',
      'share_link': 'Share Live Link',
      'share_file_closed_only': 'Cashbook must be closed before it can be shared as a finalized report file.',
      'close_now': 'Close Now',
      'cancel': 'Cancel',
      'book_name': 'Cashbook Name',
      'select_icon': 'Select Icon',
      'select_color': 'Select Theme Color',
      'save': 'Save',
      'update': 'Update',
      'delete': 'Delete',
      'edit': 'Edit',
      'status_open': 'Open',
      'status_closed': 'Closed',
      'add_book': 'Add Cashbook',
      'new_book': 'New Cashbook',
      'create_first_book': 'Create First Cashbook',
      'create_first_book_desc': 'Start tracking your finances by creating your first cashbook.',
      'start_now': 'Start Now',
      // Transactions
      'history_transactions': 'Transaction History',
      'search_placeholder': 'Search note or category...',
      'all': 'All',
      'nominal_income': 'Income Amount',
      'nominal_expense': 'Expense Amount',
      'category': 'Category',
      'transaction_date': 'Transaction Date',
      'notes_optional': 'Notes (Optional)',
      'notes_hint_income': 'Enter income description...',
      'notes_hint_expense': 'Enter expense description...',
      'detail_transaction': 'Transaction Details',
      'delete_to_trash': 'Move to Trash',
      'delete_confirm_desc': 'This item will be moved to Trash and can be restored at any time.',
      'amount': 'Amount',
      'choose_category': 'Choose Category',
      'save_transaction': 'Save Transaction',
      'edit_transaction': 'Edit Transaction',
      'enter_valid_amount': 'Please enter a valid amount',
      'please_select_category': 'Please select a category',
      'transaction_saved': 'Transaction saved successfully',
      'transaction_deleted': 'Transaction moved to trash',
      'date': 'Date',
      'time': 'Time',
      'notes': 'Notes',
      'quick_amounts': 'Quick Amounts',
      'no_transactions_found': 'No matching transactions found',
      // Report
      'financial_report': 'Financial Report',
      'this_month': 'This Month',
      'last_month': 'Last Month',
      'this_year': 'This Year',
      'custom_range': 'Custom',
      'net_balance': 'Net Balance',
      'cash_flow_comparison': 'Cash Flow Comparison',
      'expense_by_category': 'Expense by Category',
      'export_pdf': 'Export PDF',
      'export_excel': 'Export Excel',
      'no_report_data': 'No data available for this period',
      // Categories
      'income_categories': 'Income Categories',
      'expense_categories': 'Expense Categories',
      'add_category': 'Add Category',
      'edit_category': 'Edit Category',
      'category_name': 'Category Name',
      'cannot_delete_default': 'Default categories cannot be deleted',
      'delete_category_confirm': 'Are you sure you want to delete this category?',
      // Trash
      'trash_title': 'Trash',
      'tab_cashbooks': 'Cashbooks',
      'tab_transactions': 'Transactions',
      'restore': 'Restore',
      'delete_permanent': 'Delete Permanently',
      'empty_trash_cashbooks': 'No cashbooks in trash',
      'empty_trash_transactions': 'No transactions in trash',
      'restore_success': 'Data restored successfully',
      'delete_permanent_confirm': 'This data will be permanently deleted and cannot be recovered. Continue?',
      // Account
      'account_settings': 'Account & Settings',
      'drive_sync_title': 'Google Drive Cloud Sync',
      'drive_sync_desc': 'Stored in your personal data.cashbook file',
      'sync_now': 'Sync',
      'manage_categories': 'Manage Categories',
      'import_cbshare': 'Import Cashbook (.cbshare)',
      'import_cbshare_sub': 'Open files shared by others',
      'trash_menu': 'Trash',
      'app_theme': 'Theme Mode',
      'language': 'Language',
      'pin_security': 'PIN Lock',
      'biometric_security': 'Biometric Lock',
      'logout': 'Sign Out Google Account',
      'set_pin': 'Set Security PIN (6 Digits)',
      'enter_pin': 'Enter 6-digit PIN',
      'pin_set_success': 'Security PIN set successfully',
      'pin_removed': 'Security PIN removed',
      'biometric_enabled': 'Biometric lock enabled',
      'biometric_disabled': 'Biometric lock disabled',
      'system_theme': 'System',
      'light_theme': 'Light',
      'dark_theme': 'Dark',
      'select_language': 'Select Language',
    },
    'es': {
      'app_title': 'Cashbook',
      'app_tagline': 'Control Financiero Inteligente y Seguro',
      // Nav
      'nav_home': 'Inicio',
      'nav_transactions': 'Transacciones',
      'nav_report': 'Informe',
      'nav_account': 'Cuenta',
      // Home
      'total_balance': 'Saldo Total',
      'cash_in': 'Ingresos',
      'cash_out': 'Gastos',
      'add_income': 'Ingreso',
      'add_expense': 'Gasto',
      'manage_books': 'Gestionar Libros',
      'recent_transactions': 'Transacciones Recientes',
      'see_all': 'Ver Todo',
      'no_transactions': 'Aún no hay transacciones en este libro',
      'no_transactions_sub': 'Toca los botones de arriba para registrar transacciones',
      'sync_drive': 'Sincronizar con Google Drive',
      'sync_success': '¡Datos sincronizados con éxito en Google Drive!',
      'sync_failed': 'Error de sincronización, revisa tu conexión a internet.',
      'read_only_banner': 'Este libro es de solo lectura. No puedes añadir ni editar transacciones.',
      'closed_book_banner': 'Este libro está cerrado. Reábrelo para registrar nuevas transacciones.',
      // Book
      'select_book': 'Seleccionar Libro',
      'active_books': 'Libros Activos',
      'closed_books': 'Libros Cerrados',
      'close_book': 'Cerrar Libro',
      'reopen_book': 'Reabrir Libro',
      'close_book_confirm_title': '¿Cerrar este Libro?',
      'close_book_confirm_desc': 'Una vez cerrado, las transacciones no se pueden modificar hasta que se reabra.',
      'reopen_book_confirm_title': '¿Reabrir este Libro?',
      'reopen_book_confirm_desc': 'El libro se activará de nuevo permitiendo registrar nuevas transacciones.',
      'share_file': 'Compartir Archivo (.cbshare)',
      'share_link': 'Compartir Enlace en Vivo',
      'share_file_closed_only': 'El libro debe estar cerrado antes de poder compartirlo como archivo de resumen final.',
      'close_now': 'Cerrar Ahora',
      'cancel': 'Cancelar',
      'book_name': 'Nombre del Libro',
      'select_icon': 'Seleccionar Icono',
      'select_color': 'Seleccionar Color',
      'save': 'Guardar',
      'update': 'Actualizar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'status_open': 'Abierto',
      'status_closed': 'Cerrado',
      'add_book': 'Añadir Libro',
      'new_book': 'Nuevo Libro',
      'create_first_book': 'Crear Primer Libro',
      'create_first_book_desc': 'Comienza a controlar tus finanzas creando tu primer libro.',
      'start_now': 'Comenzar Ahora',
      // Transactions
      'history_transactions': 'Historial de Transacciones',
      'search_placeholder': 'Buscar nota o categoría...',
      'all': 'Todo',
      'nominal_income': 'Monto de Ingreso',
      'nominal_expense': 'Monto de Gasto',
      'category': 'Categoría',
      'transaction_date': 'Fecha de Transacción',
      'notes_optional': 'Notas (Opcional)',
      'notes_hint_income': 'Escribe descripción del ingreso...',
      'notes_hint_expense': 'Escribe descripción del gasto...',
      'detail_transaction': 'Detalles de la Transacción',
      'delete_to_trash': 'Mover a la Papelera',
      'delete_confirm_desc': 'Este elemento se moverá a la Papelera y podrá recuperarse en cualquier momento.',
      'amount': 'Monto',
      'choose_category': 'Elegir Categoría',
      'save_transaction': 'Guardar Transacción',
      'edit_transaction': 'Editar Transacción',
      'enter_valid_amount': 'Introduce un monto válido',
      'please_select_category': 'Por favor selecciona una categoría',
      'transaction_saved': 'Transacción guardada con éxito',
      'transaction_deleted': 'Transacción movida a la papelera',
      'date': 'Fecha',
      'time': 'Hora',
      'notes': 'Notas',
      'quick_amounts': 'Montos Rápidos',
      'no_transactions_found': 'No se encontraron transacciones',
      // Report
      'financial_report': 'Informe Financiero',
      'this_month': 'Este Mes',
      'last_month': 'Mes Pasado',
      'this_year': 'Este Año',
      'custom_range': 'Personalizado',
      'net_balance': 'Saldo Neto',
      'cash_flow_comparison': 'Comparación de Flujo de Caja',
      'expense_by_category': 'Gastos por Categoría',
      'export_pdf': 'Exportar PDF',
      'export_excel': 'Exportar Excel',
      'no_report_data': 'No hay datos disponibles para este período',
      // Categories
      'income_categories': 'Categorías de Ingresos',
      'expense_categories': 'Categorías de Gastos',
      'add_category': 'Añadir Categoría',
      'edit_category': 'Editar Categoría',
      'category_name': 'Nombre de Categoría',
      'cannot_delete_default': 'Las categorías predeterminadas no se pueden eliminar',
      'delete_category_confirm': '¿Estás seguro de que deseas eliminar esta categoría?',
      // Trash
      'trash_title': 'Papelera',
      'tab_cashbooks': 'Libros',
      'tab_transactions': 'Transacciones',
      'restore': 'Restaurar',
      'delete_permanent': 'Eliminar Permanentemente',
      'empty_trash_cashbooks': 'No hay libros en la papelera',
      'empty_trash_transactions': 'No hay transacciones en la papelera',
      'restore_success': 'Datos restaurados con éxito',
      'delete_permanent_confirm': 'Estos datos se eliminarán permanentemente y no se podrán recuperar. ¿Continuar?',
      // Account
      'account_settings': 'Cuenta y Configuración',
      'drive_sync_title': 'Sincronización Google Drive',
      'drive_sync_desc': 'Guardado en tu archivo personal data.cashbook',
      'sync_now': 'Sincronizar',
      'manage_categories': 'Gestionar Categorías',
      'import_cbshare': 'Importar Libro (.cbshare)',
      'import_cbshare_sub': 'Abrir archivos compartidos por otros',
      'trash_menu': 'Papelera',
      'app_theme': 'Tema',
      'language': 'Idioma',
      'pin_security': 'Bloqueo PIN',
      'biometric_security': 'Bloqueo Biométrico',
      'logout': 'Cerrar Sesión de Google',
      'set_pin': 'Configurar PIN (6 Dígitos)',
      'enter_pin': 'Introduce PIN de 6 dígitos',
      'pin_set_success': 'PIN configurado con éxito',
      'pin_removed': 'PIN desactivado',
      'biometric_enabled': 'Bloqueo biométrico activado',
      'biometric_disabled': 'Bloqueo biométrico desactivado',
      'system_theme': 'Sistema',
      'light_theme': 'Claro',
      'dark_theme': 'Oscuro',
      'select_language': 'Seleccionar Idioma',
    },
    'zh': {
      'app_title': '现金账本',
      'app_tagline': '智能安全记账管家',
      // Nav
      'nav_home': '首页',
      'nav_transactions': '交易明细',
      'nav_report': '财务报表',
      'nav_account': '账户设置',
      // Home
      'total_balance': '总资产余额',
      'cash_in': '收入',
      'cash_out': '支出',
      'add_income': '记收入',
      'add_expense': '记支出',
      'manage_books': '账本管理',
      'recent_transactions': '最近记录',
      'see_all': '查看全部',
      'no_transactions': '该账本暂无交易记录',
      'no_transactions_sub': '点击上方按钮立即记一笔',
      'sync_drive': '同步至 Google Drive',
      'sync_success': '数据已成功同步到 Google Drive！',
      'sync_failed': '同步失败，请检查网络连接。',
      'read_only_banner': '此账本为只读模式，无法添加或修改记录。',
      'closed_book_banner': '该账本已封账。如需记账请重新开启账本。',
      // Book
      'select_book': '选择账本',
      'active_books': '活动账本',
      'closed_books': '已封账本',
      'close_book': '封闭账本',
      'reopen_book': '重新开启',
      'close_book_confirm_title': '确认封闭此账本？',
      'close_book_confirm_desc': '封账后，在重新开启前将无法添加或编辑记录。',
      'reopen_book_confirm_title': '确认重新开启此账本？',
      'reopen_book_confirm_desc': '账本将被重新激活，您可以继续记账。',
      'share_file': '分享文件 (.cbshare)',
      'share_link': '分享实时链接',
      'share_file_closed_only': '账本必须先封账，才能作为总结算报表文件分享。',
      'close_now': '立即封账',
      'cancel': '取消',
      'book_name': '账本名称',
      'select_icon': '选择图标',
      'select_color': '选择主题色',
      'save': '保存',
      'update': '更新',
      'delete': '删除',
      'edit': '编辑',
      'status_open': '进行中',
      'status_closed': '已封闭',
      'add_book': '新建账本',
      'new_book': '新账本',
      'create_first_book': '创建第一个账本',
      'create_first_book_desc': '创建您的第一个账本，开启智能财务之旅。',
      'start_now': '立即开始',
      // Transactions
      'history_transactions': '历史明细',
      'search_placeholder': '搜索备注或分类...',
      'all': '全部',
      'nominal_income': '收入金额',
      'nominal_expense': '支出金额',
      'category': '分类',
      'transaction_date': '交易日期',
      'notes_optional': '备注（选填）',
      'notes_hint_income': '输入收入说明...',
      'notes_hint_expense': '输入支出说明...',
      'detail_transaction': '账目详情',
      'delete_to_trash': '移至回收站',
      'delete_confirm_desc': '此条目将移至回收站，可随时恢复。',
      'amount': '金额',
      'choose_category': '选择分类',
      'save_transaction': '保存记录',
      'edit_transaction': '编辑记录',
      'enter_valid_amount': '请输入有效金额',
      'please_select_category': '请选择分类',
      'transaction_saved': '记账成功',
      'transaction_deleted': '记录已移至回收站',
      'date': '日期',
      'time': '时间',
      'notes': '备注',
      'quick_amounts': '快捷金额',
      'no_transactions_found': '没有找到匹配的交易记录',
      // Report
      'financial_report': '财务分析',
      'this_month': '本月',
      'last_month': '上月',
      'this_year': '今年',
      'custom_range': '自定义',
      'net_balance': '净结余 / 收支差额',
      'cash_flow_comparison': '收支趋势对比',
      'expense_by_category': '分类支出构成',
      'export_pdf': '导出 PDF',
      'export_excel': '导出 Excel',
      'no_report_data': '该周期暂无财务数据',
      // Categories
      'income_categories': '收入分类',
      'expense_categories': '支出分类',
      'add_category': '添加分类',
      'edit_category': '编辑分类',
      'category_name': '分类名称',
      'cannot_delete_default': '系统预设分类无法删除',
      'delete_category_confirm': '确定要删除此分类吗？',
      // Trash
      'trash_title': '回收站',
      'tab_cashbooks': '账本',
      'tab_transactions': '交易记录',
      'restore': '恢复',
      'delete_permanent': '彻底删除',
      'empty_trash_cashbooks': '回收站中没有账本',
      'empty_trash_transactions': '回收站中没有记录',
      'restore_success': '数据恢复成功',
      'delete_permanent_confirm': '该数据将被永久删除且无法找回，是否继续？',
      // Account
      'account_settings': '账户与设置',
      'drive_sync_title': 'Google Drive 云端同步',
      'drive_sync_desc': '安全保存在个人 data.cashbook 文件中',
      'sync_now': '立即同步',
      'manage_categories': '分类管理',
      'import_cbshare': '导入账本 (.cbshare)',
      'import_cbshare_sub': '打开他人分享的账本文件',
      'trash_menu': '回收站',
      'app_theme': '界面主题',
      'language': '语言',
      'pin_security': '数字 PIN 锁',
      'biometric_security': '生物识别锁',
      'logout': '退出 Google 账号',
      'set_pin': '设置安全 PIN（6 位数）',
      'enter_pin': '输入 6 位数字 PIN',
      'pin_set_success': '安全 PIN 设置成功',
      'pin_removed': '已解除安全 PIN',
      'biometric_enabled': '生物识别锁已开启',
      'biometric_disabled': '生物识别锁已关闭',
      'system_theme': '跟随系统',
      'light_theme': '浅色',
      'dark_theme': '深色',
      'select_language': '选择语言',
    },
    'ar': {
      'app_title': 'دفتر النقدية',
      'app_tagline': 'تتبع مالي ذكي وآمن',
      // Nav
      'nav_home': 'الرئيسية',
      'nav_transactions': 'المعاملات',
      'nav_report': 'التقرير',
      'nav_account': 'الحساب',
      // Home
      'total_balance': 'إجمالي الرصيد',
      'cash_in': 'وارد',
      'cash_out': 'صادر',
      'add_income': 'إضافة دخل',
      'add_expense': 'إضافة مصروف',
      'manage_books': 'إدارة الدفاتر',
      'recent_transactions': 'أحدث المعاملات',
      'see_all': 'عرض الكل',
      'no_transactions': 'لا توجد معاملات في هذا الدفتر بعد',
      'no_transactions_sub': 'اضغط على الأزرار أعلاه لتسجيل معاملة',
      'sync_drive': 'مزامنة مع Google Drive',
      'sync_success': 'تمت المزامنة بنجاح مع Google Drive!',
      'sync_failed': 'فشلت المزامنة، يرجى التحقق من اتصال الإنترنت.',
      'read_only_banner': 'هذا الدفتر للقراءة فقط. لا يمكنك إضافة أو تعديل المعاملات.',
      'closed_book_banner': 'تم إغلاق هذا الدفتر. أعد فتحه لتسجيل معاملات جديدة.',
      // Book
      'select_book': 'اختر الدفتر',
      'active_books': 'دفاتر نشطة',
      'closed_books': 'دفاتر مغلقة',
      'close_book': 'إغلاق الدفتر',
      'reopen_book': 'إعادة فتح الدفتر',
      'close_book_confirm_title': 'هل تريد إغلاق هذا الدفتر؟',
      'close_book_confirm_desc': 'بمجرد الإغلاق، لا يمكن إضافة أو تعديل المعاملات حتى يتم إعادة فتحه.',
      'reopen_book_confirm_title': 'هل تريد إعادة فتح هذا الدفتر؟',
      'reopen_book_confirm_desc': 'سيتم إعادة تنشيط الدفتر مما يتيح لك تسجيل معاملات جديدة.',
      'share_file': 'مشاركة ملف (.cbshare)',
      'share_link': 'مشاركة رابط مباشر',
      'share_file_closed_only': 'يجب إغلاق الدفتر أولاً قبل مشاركته كملف تقرير نهائي.',
      'close_now': 'إغلاق الآن',
      'cancel': 'إلغاء',
      'book_name': 'اسم الدفتر',
      'select_icon': 'اختر أيقونة',
      'select_color': 'اختر لون المظهر',
      'save': 'حفظ',
      'update': 'تحديث',
      'delete': 'حذف',
      'edit': 'تعديل',
      'status_open': 'مفتوح',
      'status_closed': 'مغلق',
      'add_book': 'إضافة دفتر نقدي',
      'new_book': 'دفتر جديد',
      'create_first_book': 'أنشئ دفترك الأول',
      'create_first_book_desc': 'ابدأ بتتبع أموالك عبر إنشاء أول دفتر نقدي لك.',
      'start_now': 'ابدأ الآن',
      // Transactions
      'history_transactions': 'سجل المعاملات',
      'search_placeholder': 'بحث عن ملاحظة أو فئة...',
      'all': 'الكل',
      'nominal_income': 'مبلغ الدخل',
      'nominal_expense': 'مبلغ المصروف',
      'category': 'الفئة',
      'transaction_date': 'تاريخ المعاملة',
      'notes_optional': 'ملاحظات (اختياري)',
      'notes_hint_income': 'أدخل وصف الدخل...',
      'notes_hint_expense': 'أدخل وصف المصروف...',
      'detail_transaction': 'تفاصيل المعاملة',
      'delete_to_trash': 'نقل إلى المهملات',
      'delete_confirm_desc': 'سيتم نقل هذا العنصر إلى سلة المهملات ويمكن استعادته في أي وقت.',
      'amount': 'المبلغ',
      'choose_category': 'اختر الفئة',
      'save_transaction': 'حفظ المعاملة',
      'edit_transaction': 'تعديل المعاملة',
      'enter_valid_amount': 'يرجى إدخال مبلغ صحيح',
      'please_select_category': 'يرجى اختيار فئة',
      'transaction_saved': 'تم حفظ المعاملة بنجاح',
      'transaction_deleted': 'تم نقل المعاملة إلى سلة المهملات',
      'date': 'التاريخ',
      'time': 'الوقت',
      'notes': 'الملاحظات',
      'quick_amounts': 'مبالغ سريعة',
      'no_transactions_found': 'لم يتم العثور على معاملات مطابقة',
      // Report
      'financial_report': 'التقرير المالي',
      'this_month': 'هذا الشهر',
      'last_month': 'الشهر الماضي',
      'this_year': 'هذا العام',
      'custom_range': 'مخصص',
      'net_balance': 'صافي الرصيد',
      'cash_flow_comparison': 'مقارنة التدفق النقدي',
      'expense_by_category': 'المصروفات حسب الفئة',
      'export_pdf': 'تصدير PDF',
      'export_excel': 'تصدير Excel',
      'no_report_data': 'لا توجد بيانات متاحة لهذه الفترة',
      // Categories
      'income_categories': 'فئات الدخل',
      'expense_categories': 'فئات المصروفات',
      'add_category': 'إضافة فئة',
      'edit_category': 'تعديل الفئة',
      'category_name': 'اسم الفئة',
      'cannot_delete_default': 'لا يمكن حذف الفئات الافتراضية للنظام',
      'delete_category_confirm': 'هل أنت متأكد من حذف هذه الفئة؟',
      // Trash
      'trash_title': 'سلة المهملات',
      'tab_cashbooks': 'الدفاتر',
      'tab_transactions': 'المعاملات',
      'restore': 'استعادة',
      'delete_permanent': 'حذف نهائي',
      'empty_trash_cashbooks': 'لا توجد دفاتر في سلة المهملات',
      'empty_trash_transactions': 'لا توجد معاملات في سلة المهملات',
      'restore_success': 'تمت استعادة البيانات بنجاح',
      'delete_permanent_confirm': 'سيتم حذف هذه البيانات نهائياً ولا يمكن استرجاعها. متابعة؟',
      // Account
      'account_settings': 'الحساب والإعدادات',
      'drive_sync_title': 'مزامنة السحابة مع Google Drive',
      'drive_sync_desc': 'محفوظ بأمان في ملف data.cashbook الشخصي',
      'sync_now': 'مزامنة',
      'manage_categories': 'إدارة الفئات',
      'import_cbshare': 'استيراد دفتر (.cbshare)',
      'import_cbshare_sub': 'فتح الملفات المشتركة من الآخرين',
      'trash_menu': 'سلة المهملات',
      'app_theme': 'المظهر',
      'language': 'اللغة',
      'pin_security': 'رمز PIN السري',
      'biometric_security': 'القفل الحيوي',
      'logout': 'تسجيل الخروج من حساب Google',
      'set_pin': 'تعيين رمز PIN (6 أرقام)',
      'enter_pin': 'أدخل رمز PIN المكون من 6 أرقام',
      'pin_set_success': 'تم تعيين رمز PIN بنجاح',
      'pin_removed': 'تمت إزالة رمز PIN',
      'biometric_enabled': 'تم تفعيل القفل الحيوي',
      'biometric_disabled': 'تم تعطيل القفل الحيوي',
      'system_theme': 'النظام',
      'light_theme': 'فاتح',
      'dark_theme': 'داكن',
      'select_language': 'اختر اللغة',
    },
  };

  String tr(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['id']?[key] ??
        key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['id', 'en', 'es', 'zh', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
